thanks page
sauloco/rusticit pull request #24
Opened 2021-03-08 14:24 UTC by florsoncini

thanks svg //
index.html //
thanks sentences //
style thanks //

2021-03-12 22:05 UTC, sauloco commented
Agreguenle el thanks al comando de `build` asi cuando hacen el push lo podemos probar.

2021-03-12 22:10 UTC, sauloco requested changes

2021-03-12 22:10 UTC, sauloco commented on package.json
>      "build": "parcel build src/*.html src/presentador/*/*.html",
Add thanks here

2021-03-12 22:10 UTC, sauloco commented on src/thanks/script.js
> +// cómo importar del script principal sin errores en consola
definitivamente hay que resolverlo, no repetir el code.

2021-03-12 22:10 UTC, sauloco commented on src/thanks/script.js
> +// cómo importar del script principal sin errores en consola
les recomiendo crear un archivo nuevo con estas funciones que van a ser compartidas entre varios scripts, exportar las funciones alli y luego importarlas desde el script principal y desde este archivo tambien.

2021-03-15 18:18 UTC, sauloco requested changes

2021-03-15 18:18 UTC, sauloco commented on src/thanks/index.html
> +          <a href="https://rusticit.com/#want_more">Contact us</a> for specific
deberia decir `/#want_more` solamente. No necesitas repetir el dominio, con la ruta relativa alcanza.

2021-03-15 18:18 UTC, sauloco commented on src/i18n/sentences.js
> +      "El pago por <span class='service-name'></span> se encuentra pendiente aún. Si necesita más información <a href= 'https://rusticit.com/#want_more'>contáctenos</a>.",
deberia decir `/#want_more` solamente. No necesitas repetir el dominio, con la ruta relativa alcanza.

2021-03-15 18:22 UTC, MartinSoncini commented on src/thanks/script.js
> +// cómo importar del script principal sin errores en consola
esa pensaba yo, busqué otra manera pero no encontré, capaz vos sabías algo

2021-03-15 19:12 UTC, MartinSoncini commented on src/thanks/index.html
> +          <a href="https://rusticit.com/#want_more">Contact us</a> for specific
no estaría funcionando, por lo menos en el deploy

2021-05-12 16:18 UTC, merged